startDelaySeconds: 0
lowercaseOutputName: true
lowercaseOutputLabelNames: true
rules:
  - pattern: "kafka.server<type=(.+), name=(.+)PerSec\\w*><>Count"
    name: "kafka_server_$1_$2_total"
    type: COUNTER
    help: "Kafka metric $1 $2 per second"
  - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
    name: "kafka_server_$1_$2"
    type: GAUGE
